"""Atlas UI — the orb: what Atlas is doing, and how it feels, at a glance.

The browser draws; this package decides *what* it is told.  `protocol.py` is the
wire schema (generated to TypeScript), `theme.py` is the meaning (state → motion,
mood → hue), `hub.py` is the pipeline with its throttles, and `bridge.py` +
`window.py` are the two optional shells around it — FastAPI/WebSocket and
pywebview/WebView2.  Import this package and none of those extras is required.
"""

from atlas_ui.assets import AssetReport, check_assets, delimiters_balanced, orb_path, strip_code
from atlas_ui.bridge import (
    UI_TOPICS,
    EventBridge,
    bridge_available,
    bridge_missing,
    new_token,
    orb_dir,
    status_rows,
)
from atlas_ui.hub import LEVEL_HZ, QUEUE_SIZE, TOKEN_BATCH_S, HubStats, UiHub, UiSession
from atlas_ui.protocol import (
    MESSAGE_TYPES,
    MOOD_HUES,
    PROTOCOL_VERSION,
    CaptionMessage,
    ConfirmMessage,
    DegradedMessage,
    HelloMessage,
    LevelMessage,
    MoodMessage,
    StateMessage,
    ToolMessage,
    UiMessage,
    message_for_topic,
    typescript,
)
from atlas_ui.theme import (
    CAPTION_FADE_S,
    ORB_STATES,
    OVERLAY_STATES,
    STATE_MOTIONS,
    ThemeEngine,
    clamp_caption,
    is_rtl,
    state_report,
    tool_phrase,
)
from atlas_ui.window import (
    HOTKEYS,
    ORB_SIZE,
    PANEL_SIZE,
    HotkeyManager,
    InstanceLock,
    OrbWindow,
    TrayIcon,
    WindowState,
    hotkey_bindings,
    hotkeys_available,
    hotkeys_missing,
    tray_available,
    tray_missing,
    ui_state_dir,
    window_available,
    window_missing,
)

__all__ = [
    "CAPTION_FADE_S",
    "HOTKEYS",
    "LEVEL_HZ",
    "MESSAGE_TYPES",
    "MOOD_HUES",
    "ORB_SIZE",
    "ORB_STATES",
    "OVERLAY_STATES",
    "PANEL_SIZE",
    "PROTOCOL_VERSION",
    "QUEUE_SIZE",
    "STATE_MOTIONS",
    "TOKEN_BATCH_S",
    "UI_TOPICS",
    "AssetReport",
    "CaptionMessage",
    "ConfirmMessage",
    "DegradedMessage",
    "EventBridge",
    "HelloMessage",
    "HotkeyManager",
    "HubStats",
    "InstanceLock",
    "LevelMessage",
    "MoodMessage",
    "OrbWindow",
    "StateMessage",
    "ThemeEngine",
    "ToolMessage",
    "TrayIcon",
    "UiHub",
    "UiMessage",
    "UiSession",
    "WindowState",
    "bridge_available",
    "bridge_missing",
    "check_assets",
    "clamp_caption",
    "delimiters_balanced",
    "hotkey_bindings",
    "hotkeys_available",
    "hotkeys_missing",
    "is_rtl",
    "message_for_topic",
    "new_token",
    "orb_dir",
    "orb_path",
    "state_report",
    "status_rows",
    "strip_code",
    "tool_phrase",
    "tray_available",
    "tray_missing",
    "typescript",
    "ui_state_dir",
    "window_available",
    "window_missing",
]
